[[main]]
  identifier = "posts"
  name = "Posts"
  url = "/blog/posts/"
  weight = 10

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

[[main]]
  identifier = "profile"
  name = "Profile"
  url = "/"
  weight = 40

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 50
